/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bmwM8.gltf 
Author: blakebella (https://sketchfab.com/blake2theback)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd-4.0/)
Source: https://sketchfab.com/3d-models/bmw-m8-competition-widebody-026f3f65371b428fb49b5d0e0029eaf6
Title: BMW M8 Competition Widebody
*/

import React, { useRef, useEffect, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { useLoader } from '@react-three/fiber';
import * as THREE from 'three'; 

function Model(props) {
  const { nodes, materials } = useGLTF('/bmwM8.gltf')
  
  // Debug: Log available objects and materials
  useEffect(() => {
    console.log('BMW M8 - Available nodes:', Object.keys(nodes));
    console.log('BMW M8 - Available materials:', Object.keys(materials));
    console.log('BMW M8 - Custom colors:', props.customColors);
    console.log('BMW M8 - Material prop:', props.material);
  }, [nodes, materials, props.customColors, props.material]);
  
  // Handle material wrapping with proper error handling
  const customMaterial = useMemo(() => {
    if (props.material && props.material !== "null") {
      try {
        const texture = useLoader(TextureLoader, props.material);
        return new THREE.MeshBasicMaterial({
          map: texture,
          transparent: false,
          side: THREE.DoubleSide
        });
      } catch (error) {
        console.error('Error loading texture:', error);
        return null;
      }
    }
    return null;
  }, [props.material]);

  // Apply custom material to body parts if available
  useEffect(() => {
    if (customMaterial && materials.BMW_M8RewardRecycled_2020Paint_Material) {
      materials.BMW_M8RewardRecycled_2020Paint_Material = customMaterial;
    }
  }, [customMaterial, materials.BMW_M8RewardRecycled_2020Paint_Material]);

  // Ensure customColors has default values
  const customColors = props.customColors || {};
  const bodyColor = customColors.body || "#0066cc";
  const accessoriesColor = customColors.accesoriesColor || "#000000";
  const rimsColor = customColors.rimsColor || "#000000";

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/* Carbon Fiber Accessories */}
        <lineSegments geometry={nodes.Object_6.geometry} material={materials.BMW_M8RewardRecycled_2020Carbon1_Material} material-color={accessoriesColor}/>
        <lineSegments geometry={nodes.Object_7.geometry} material={materials.BMW_M8RewardRecycled_2020Coloured_Material} material-color={accessoriesColor}/>
        
        {/* Base Materials - Fixed */}
        <lineSegments geometry={nodes.Object_17.geometry} material={materials.BMW_M8RewardRecycled_2020Base_Material} material-color={"black"}/>
        <mesh geometry={nodes.Object_2.geometry} material={materials.BMW_M8RewardRecycled_2020BadgeB_Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.BMW_M8RewardRecycled_2020Base_Material} material-color={"black"}/>
        <mesh geometry={nodes.Object_18.geometry} material={materials.BMW_M8RewardRecycled_2020Base_Material} material-color={"black"}/>
        
        {/* Accessories - License Plate, Lights */}
        <mesh geometry={nodes.Object_3.geometry} material={materials.BMW_M8RewardRecycled_2020LicensePlateDefaultA_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_4.geometry} material={materials.BMW_M8RewardRecycled_2020LightA_Material} />
        
        {/* Grilles - Accessories Color */}
        <mesh geometry={nodes.Object_8.geometry} material={materials.BMW_M8RewardRecycled_2020Grille3A_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_9.geometry} material={materials.BMW_M8RewardRecycled_2020Grille4A_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_10.geometry} material={materials.BMW_M8RewardRecycled_2020Grille5A_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_11.geometry} material={materials.BMW_M8RewardRecycled_2020Grille6A_Material} material-color={accessoriesColor}/>
        
        {/* Interior and Seat Belts - Fixed */}
        <mesh geometry={nodes.Object_12.geometry} material={materials.BMW_M8RewardRecycled_2020SeatBelt_Material} material-color={"black"}/>
        <mesh geometry={nodes.Object_13.geometry} material={materials.BMW_M8RewardRecycled_2020WindowInside_Material} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.BMW_M8RewardRecycled_2020InteriorColourZoneA_Material} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.BMW_M8RewardRecycled_2020InteriorTillingColourZoneA_Material} />
        
        {/* Lights - Fixed */}
        <mesh geometry={nodes.Object_15.geometry} material={materials.redlight} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.whitelight} />
        
        {/* Carbon Fiber Parts - Accessories Color */}
        <mesh geometry={nodes.Object_19.geometry} material={materials.BMW_M8RewardRecycled_2020Carbon1_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_20.geometry} material={materials.BMW_M8RewardRecycled_2020Carbon1_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_21.geometry} material={materials.BMW_M8RewardRecycled_2020Carbon1_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_22.geometry} material={materials.BMW_M8RewardRecycled_2020Carbon1_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_23.geometry} material={materials.BMW_M8RewardRecycled_2020Carbon1_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_24.geometry} material={materials.BMW_M8RewardRecycled_2020Carbon1_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_25.geometry} material={materials.BMW_M8RewardRecycled_2020Carbon1_Material} material-color={accessoriesColor}/>
        
        {/* Colored Parts - Accessories Color */}
        <mesh geometry={nodes.Object_26.geometry} material={materials.BMW_M8RewardRecycled_2020Coloured_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_27.geometry} material={materials.BMW_M8RewardRecycled_2020Coloured_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_28.geometry} material={materials.BMW_M8RewardRecycled_2020Coloured_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_29.geometry} material={materials.BMW_M8RewardRecycled_2020Coloured_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_30.geometry} material={materials.BMW_M8RewardRecycled_2020Coloured_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_31.geometry} material={materials.BMW_M8RewardRecycled_2020Coloured_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_32.geometry} material={materials.BMW_M8RewardRecycled_2020Coloured_Material} material-color={accessoriesColor}/>
        
        {/* Engine Parts - Accessories Color */}
        <mesh geometry={nodes.Object_33.geometry} material={materials.BMW_M8RewardRecycled_2020EngineA_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_34.geometry} material={materials.BMW_M8RewardRecycled_2020EngineA_Material} material-color={accessoriesColor}/>
        
        {/* Grille and Interior - Accessories Color */}
        <mesh geometry={nodes.Object_35.geometry} material={materials.BMW_M8RewardRecycled_2020Grille2A_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_36.geometry} material={materials.BMW_M8RewardRecycled_2020InteriorA_Material} material-color={accessoriesColor}/>
        <mesh geometry={nodes.Object_37.geometry} material={materials.BMW_M8RewardRecycled_2020InteriorA_Material} material-color={accessoriesColor}/>
        
        {/* Body Paint - Apply custom material or color */}
        <mesh geometry={nodes.Object_39.geometry} material={materials.BMW_M8RewardRecycled_2020Paint_Material} material-color={customMaterial ? undefined : bodyColor}/>
        <mesh geometry={nodes.Object_40.geometry} material={materials.BMW_M8RewardRecycled_2020Paint_Material} material-color={customMaterial ? undefined : bodyColor}/>
        <mesh geometry={nodes.Object_41.geometry} material={materials.BMW_M8RewardRecycled_2020Paint_Material} material-color={customMaterial ? undefined : bodyColor}/>
        <mesh geometry={nodes.Object_42.geometry} material={materials.BMW_M8RewardRecycled_2020Paint_Material} material-color={customMaterial ? undefined : bodyColor}/>
        <mesh geometry={nodes.Object_43.geometry} material={materials.BMW_M8RewardRecycled_2020Paint_Material} material-color={customMaterial ? undefined : bodyColor}/>
        <mesh geometry={nodes.Object_44.geometry} material={materials.BMW_M8RewardRecycled_2020Paint_Material} material-color={customMaterial ? undefined : bodyColor}/>
        
        {/* Windows - Fixed */}
        <mesh geometry={nodes.Object_45.geometry} material={materials.BMW_M8RewardRecycled_2020Window_Material} />
        
        {/* Badges - Fixed Yellow */}
        <mesh geometry={nodes.Object_46.geometry} material={materials['badge.001']} material-color={"yellow"}/>
        <mesh geometry={nodes.Object_47.geometry} material={materials.col2} material-color={"yellow"}/>
        
        {/* Wheels and Rims - Rims Color */}
        <mesh geometry={nodes.Object_48.geometry} material={materials['rim.001']} material-color={rimsColor}/>
        <mesh geometry={nodes.Object_49.geometry} material={materials['rim.001']} material-color={rimsColor}/>
        <mesh geometry={nodes.Object_50.geometry} material={materials['rim.001']} material-color={rimsColor}/>
        <mesh geometry={nodes.Object_51.geometry} material={materials['rim.001']} material-color={rimsColor}/>
        <mesh geometry={nodes.Object_52.geometry} material={materials['rim.001']} material-color={rimsColor}/>
        <mesh geometry={nodes.Object_53.geometry} material={materials['rim.001']} material-color={rimsColor}/>
        <mesh geometry={nodes.Object_54.geometry} material={materials['rim.001']} material-color={rimsColor}/>
        <mesh geometry={nodes.Object_55.geometry} material={materials['rim.001']} material-color={rimsColor}/>
        
        {/* Brake Rotors - Rims Color */}
        <mesh geometry={nodes.Object_56.geometry} material={materials.rotor} material-color={rimsColor}/>
        
        {/* Tires - Fixed Black */}
        <mesh geometry={nodes.Object_57.geometry} material={materials['tire.001']} material-color={"black"}/>
      </group>
    </group>
  )
}

useGLTF.preload('/bmwM8.gltf')
export default Model;
